### PR TITLE
generateSecureBundleURLWithResponse check errors

### PR DESCRIPTION
**Pull request by wizardishungry**

### CODE REVIEW

**Review by mpenick — APPROVED** [review]

**Comment by kokizzu** [comment]
fixes https://github.com/datastax/cql-proxy/issues/109

**Comment by absurdfarce** [comment]
@wizardishungry Thanks for the contribution!  This change looks good (and makes a great deal of sense).

Have you signed the Contributor License Agreement for contributions to DataStax open source projects? If not you can find it at https://cla.datastax.com/. Thanks!

**Comment by StevenLacerda** [comment]
@bogdanprodanj Can you also get a CLA signed for this one? Thanks!

**Comment by bogdanprodanj** [comment]
> @bogdanprodanj Can you also get a CLA signed for this one? Thanks!

I can't, it says Status: Completed

**Comment by absurdfarce** [comment]
@bogdanprodanj has indeed signed the CLA form; he had to do so as part of the process for PR #111.  This PR was created by @wizardishungry, however, so we'd need a signed CLA from him to merge it.

I'll ask around and see if there's anything we can do to help make this happen.

**Comment by wizardishungry** [comment]
I've signed the CLA!

**Comment by absurdfarce** [comment]
Excellent, thank you @wizardishungry!  This change is a clear improvement on it's face so I'll merge it straightaway.

**Pull request merged**
